apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
data:
  REACT_APP_API: "http://server-service:8080/api/tasks" 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  PORT: "3000"


