apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: 777229646641.dkr.ecr.us-east-1.amazonaws.com/wajeehs-ecr-repo:server
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: server-config
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: server-secret
                key: mongodb-url
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: ClusterIP 