name: To-do App DevOps Pipeline
on:
  push:
    branches: [ dev ]

jobs:
  deploy-iac:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Store Branch Name
        run: echo "Branch_Name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: |
          cd iaac
          terraform init

      - name: Plan Terraform changes
        run: |
          cd iaac
          terraform plan -var-file="./iaac/terraformtfvars/${Branch_Name}.tfvars" > plan.out

      - name: Prompt for confirmation
        run: |
          cd iaac
          cat plan.out
          echo "Do you want to apply the Terraform changes? (yes/no)"
          read apply_confirmation
          if [ "$apply_confirmation" == "yes" ]; then
            terraform apply -var-file="./iaac/terraform-tfvars/${Branch_Name}.tfvars" --auto-approve
          else
            echo "Terraform apply skipped."
          fi

      - name: Save ECR repository name
        run: echo "ECR_REPOSITORY_NAME=$(terraform output -raw module.ecr_repo.ecr_repository_url)" >> $GITHUB_ENV`
