name: Deploy to EKS

env:
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get install -y curl
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Configure kubeconfig
        run: | 
          aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name $EKS_CLUSTER_NAME

      - name: Update deployment manifest files
        run: |
          chmod +x ./src/get_item.sh
          decremented_client_value=$(( $(./src/get_item.sh Client) - 1 ))
          decremented_server_value=$(( $(./src/get_item.sh Server) - 1 ))

          pwd
          sed -i "s|\(image:.*\)\/wajeehs-ecr-repo:\(.*\)|\1\/wajeehs-ecr-repo:client-v$decremented_client_value|g" ./eks/client.yaml
          sed -i "s|\(image:.*\)\/wajeehs-ecr-repo:\(.*\)|\1\/wajeehs-ecr-repo:server-v$decremented_server_value|g" ./eks/server.yaml

      - name: Deploy to EKS
        run: |
          cd eks
          kubectl apply -f . -n sl-devops --validate=false 
