name: Terraform AWS Deployment

on:
#   push:
#     branches:
#       - dev
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Confirm deployment'
        required: true
        default: 'no'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Store Branch Name
      run: echo "Branch_Name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Initialize Terraform
      working-directory: iaac
      run: terraform init

    - name: Plan infrastructure changes
      working-directory: iaac
      run: terraform plan -var-file="terraform-tfvars/${Branch_Name}.tfvars" > plan.out

    - name: Prompt for confirmation
      if: ${{ github.ref == 'refs/heads/dev' && github.event.inputs.confirmation == 'yes' }}
      working-directory: iaac
      run: echo "User confirmed deployment"

    - name: Deploy infrastructure
      if: ${{ github.ref == 'refs/heads/dev' && github.event.inputs.confirmation == 'yes' }}
      working-directory: iaac
      run: terraform apply -var-file="terraform-tfvars/${Branch_Name}.tfvars" --auto-approve
