name: Build Docker Images

env:
  ECR_REPO_URL: ${{ vars.ECR_REPOSITORY_URL }}

on:
  push:
    # paths:
    #   - 'src/client/**'
    #   - 'src/server/**'
    branches:
      - dev
#   workflow_dispatch:
#     inputs:
#       build_response:
#         description: 'Confirm Build'
#         required: true
#         default: 'no'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag and push the client docker image
      if: contains(github.event_path, 'src/client/')
      run: |
        docker build -t $ECR_REPO_URL:client ./src/client
        if [ $? -eq 0 ]; then
          docker push $ECR_REPO_URL/client
        else
          echo "Build failed."
          exit 1
        fi

    - name: Build, tag and push the server docker image
      if: contains(github.event_path, 'src/server/')
      run: |
        docker build -t $ECR_REPO_URL:server ./src/server
        if [ $? -eq 0 ]; then
          docker push $ECR_REPO_URL:server
        else
          echo "Build failed."
          exit 1
        fi
    
